### PR TITLE
Circuit breaker implementation

### PR DESCRIPTION
**Pull request by mclausen**
Hi Rebus Team,

The following PR is the first stab at implementing a circuit breaker feature described in #882. The feature is not entirely done, so I would love some help and feedback getting the last details in place.

My motivation for this is that, after the issue was mentioned we internally in our company had a couple of discussions on where this could be applied. We found some very interesting use-cases that could potentially save a ton of workload, clean-up and headaches. So without much consideration I went ahead and took the first stab at the feature and to see where i goes.

The idea is pretty simple, Based on a known exception Type, trip and trigger a circuit breaker. In a case where the circuit opens, we would `SetNumberOfWorkers(0)` to ensure that Rebus has stopped processing messages for the time being.

### Configuration
This is how i imagine how you would configure circuit breakers.
```cs
 var bus = Configure.With(...) 
     .Options(o => 
     { 
          o.EnableCircuitBreakers(c => c.OpenOn<MyExternalServiceException>(attempts: 5
                                                                       , trackingPeriodInSeconds: 10
                                                                       , halfOpenPeriodInSeconds: 150
                                                                       , resetIntervalInSeconds: 300)); 
     })
     .Start(); 
```

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mclausen** [comment]
Continuation of https://github.com/rebus-org/Rebus/pull/891

**Comment by mclausen** [comment]
Hi @mookid8000!
I am finally close to get everything up and running, however there are two challenges that I am unsure of how works inside rebus.

🌵  First the `IInitializable` interface. 
In order to get my reset interval timer to work, I've implemented this interface to postpone the scheduler until Rebus deems it ready. I would think that it should be enough to just register `IInitializable` in Injectionist, but the `Initialize()` Method is never called. Do i need to do this manually, or is there a trick to it? 🤔 

🌵  Secondly I am injecting the `RebusBus` directly into the `MainCircuitBreaker` in order to be able to control the amount of workers Rebus is running with. When i try to debug however, i can see that i hit the `_rebusBus.SetNumberOfWorkers()` [Link](https://github.com/rebus-org/Rebus.CircuitBreaker/pull/1/files#diff-8a78c5de1cea04d79ffc8dd74a6f0618R80), but when I Assert the count of workers in the test suite, the amount of workers does not match my expected count. I believe that there are some concurrency challenges at play, but i would love to get some feedback on this one 🖐️ 

Besides that I think its done, so I would love you to give it a swing and see if anything is missing 🎉 🚀 🙌

**Comment by mookid8000** [comment]
Excellent work so far! 👍 I'll merge this, and then we'll play around with it and see where it goes 🙂

**Comment by mookid8000** [comment]
Hey @mclausen , I've fixed a couple of things... first off, I've removed the `ICircuitBreaker` interface from `MainCircuitBreaker`, because it would never make sense for it to manage itself, and in my view it looks more like a "circuit breaker manager", or something like that. 🙂 (didn't rename it though)

Then I've fixed how the bus is injected – it's not possible to inject `IBus` directly, because that creates a circular dependency (to resolve the bus, Injectionist must build the circuit breaker, but to resolve the circuit breaker, Injectionist must build the bus.... 🙄 )

Finally I fixed the deadlock situation that would arise from trying to set the number of workers to 0 from within a message handler... the problem was that Rebus will wait for currently executing handlers to finish their work before returning from `SetNumberOfWorkers`, and it would block the current handler while waiting... 💥 deadlock.

The first integration test passes now, so I added another one that should test that the circuit breaker could reset after a while, but it didn't pass.... maybe you can tell what's wrong?

**Comment by mclausen** [comment]
Thanks for the feedback 🤠 

The circuit breaker is resetting itself after a specified Period. However as I mentioned above I had some challenges registering the `IInitializable` and getting it to `Initialize();`

Once it's started, it will enumerate the registered circuit breakers every 5 seconds to see whether their internal state has changed and reset accordingly. 🍰

**Comment by mookid8000** [comment]
> (...) However as I mentioned above I had some challenges registering the IInitializable and getting it to Initialize();

oh,  I fixed that too 🙂 but it still doesn't seem to reset

**Comment by mclausen** [comment]
I'll be damned ⚡. I will have to setup a test project locally and work it out 👍

**Pull request merged**
